#%RAML 1.0
---
title: crystalorb types
uses:
    p: ./primitives.raml
types:
    UserCreated:
        type: object
        properties:
            userId:
                required: true
                type: integer
    MapCreationRequest:
        type: object
        properties:
            imageId:
                required: true
                type: integer
    MapCreatedResponse:
        type: object
        properties:
            mapId:
                required: true
                type: integer
    GetMapResponse:
        type: object
        properties:
            imageId:
                required: true
                type: integer
            labels:
                required: false
                type: array
                items:
                    type: object
                    properties:
                        labelId:
                            required: true
                            type: integer
                        position:
                            required: true
                            type: p.Position
    GetMyMapsResponse:
        type: object
        properties:
            mapIds:
                required: true
                type: array
                items: integer
    PutLabelRequest:
        type: object
        properties:
            message:
                required: true
                type: string
            position:
                required: true
                type: p.Position
    FileUploadResponse:
        type: object
        properties:
            fileId:
                type: integer
