#%RAML 1.0
---
title: crystalorb types
uses:
    p: ../types/primitives.raml
traits:
    NotFound:
        responses:
            404:
                description: We couldn't find requested resource
                body:
                    application/json:
                        type: p.Error
    Conflict:
        responses:
            409:
                description: <<description>>
                body:
                    application/json:
                        type: p.Error
    Unprocessable:
        responses:
            422:
                description: <<description>>
                body:
                    application/json:
                        type: p.Error
    Fatal:
        responses:
            500:
                description: Something bad happened
                body:
                    application/json:
                        type: p.Error
