#%RAML 1.0
---
title: crystalorb types
types:
    Error:
        type: object
        properties:
            code:
                required: true
                type: string
            message:
                required: true
                type: string
    User:
        type: object
        properties:
            email:
                required: true
                type: string
            password:
                required: true
                type: string
    UserCreated:
        type: object
        properties:
            userId:
                required: true
                type: integer
    MapCreationRequest:
        type: object
        properties:
            imageId:
                required: true
                type: integer
    MapCreatedResponse:
        type: object
        properties:
            mapId:
                required: true
                type: integer
    GetMapResponse:
        type: object
        properties:
            imageId:
                required: true
                type: integer
            labelIds:
                required: false
                type: array
    PutLabelRequest:
        type: object
        properties:
            message:
                required: true
                type: string
            position:
                required: true
                type: object
                properties:
                    x:
                        required: true
                        type: integer
                    y:
                        required: true
                        type: integer
    FileUploadResponse:
        type: object
        properties:
            fileId:
                type: integer
