#%RAML 1.0
---
title: crystalorb
baseUri: https://crystalorb.madetara.dev/api/{version}
version: v1
uses:
    t: types.raml
    e: traits/errors.raml

/users:
    post:
        description: |
            Creates new user
        is: [
            e.Conflict: {description: "User with specified email already exists"},
            e.Fatal
        ]
        body:
            application/json:
                type: t.User
                example: |
                    {
                        "email": "johndoe@example.com",
                        "password": "Qwerty123!"
                    }
        responses:
            201:
                body:
                    application/json:
                        type: t.UserCreated

/maps:
    post:
        description: |
            Creates new map
        is: [
            e.Unprocessable: {description: "Failed to create map with given properties"},
            e.Fatal
        ]
        body:
            application/json:
                type: t.MapCreationRequest
        responses:
            201:
                body:
                    application/json:
                        type: t.MapCreatedResponse
    /{id}:
        get:
            description: |
                Gets map info
            is: [e.NotFound, e.Fatal]
            responses:
                200:
                    body:
                        application/json:
                            type: t.GetMapResponse
        /labels:
            put:
                description: |
                    Adds label to the map
                is: [e.NotFound, e.Fatal]
                body:
                    application/json:
                        type: t.PutLabelRequest
                responses:
                    204:
            /{id}:
                delete:
                    description: |
                        Deletes label from the map
                    is: [e.NotFound, e.Fatal]
                    responses:
                        204:

/files:
    post:
        description: |
            Upload new file
        body:
            application/octet-stream:
        is: [e.Fatal]
        responses:
            201:
                body:
                    application/json:
                        type: t.FileUploadResponse
    /{id}:
        get:
            description: |
                Gets file
            is: [e.NotFound, e.Fatal]
            responses:
                200:
                    body:
                        application/octet-stream:
        put:
            description: |
                Updates file
            is: [e.NotFound, e.Fatal]
            responses:
                204:
